config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  devise_for :users
  resources :posts, only: [:index, :show]
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      # Success
      redirect_to root_path, notice: "Add Post Successfully."
    else
      # Failed
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <%= link_to "SPREX", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse navbar-right">
            <ul class="nav navbar-nav">
                <li><%= link_to "Home", root_path %></li>
                <li>
                    <% if current_user %>
                        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                    <% else %>
                        <%= link_to "Login", new_user_session_path %>
                    <% end %>
                </li>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CmsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <%= render 'layouts/header' %>
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>" role="alert">
                <%= value %>
            </div>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %> <br />

    <%= f.label :content, "Content" %>
    <%= f.text_area :content %> <br />

    <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<div class="row">
    <div class="col-md-12">
        <% @posts.each do |post| %>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <%= link_to(post) do %>
                        <%= post.title %>
                    <% end %>
                </div>
                <div class="panel-body">
                    <%= post.content %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

<br />
<%= link_to "Back", posts_path %>

app/views/posts/show.html.erb
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h2>
            <%= @post.title %>
        </h2>
        <span><%= @post.created_at.strftime('%B %d, %Y') %> by </span>
        <p>
            <%= @post.content %>
        </p>
    </div>
</div>